version: '3.6'

services:
  web:
    build: ./src
    restart: always
    command: uwsgi --http :8000 --module srv.web:app --workers 2 --threads 2
    volumes:
      - ./src:/srv:delegated
    env_file:
      - ./.env
    ports:
      - 80:8000

  worker:
    build: ./src
    restart: always
    command: celery -A srv.tasks:celery worker
    volumes:
      - ./src:/srv:delegated
    environment:
      - C_FORCE_ROOT=on
    env_file:
      - ./.env
    links:
      - redis

  flower:
    build: ./src
    restart: always
    command: celery -A srv.tasks:celery flower --port=5555
    volumes:
      - ./src:/srv:delegated
    links:
      - redis
    env_file:
      - ./.env
    ports:
      - 5555:5555

  redis:
    image: redis:4-alpine

  # Зачем в этой схеме нужен Nginx я пока не решил
  #nginx:
  #  image: nginx:1.13-alpine
  #  volumes:
  #    - ./dist/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #  depends_on:
  #    - hook_catcher
  #  ports:
  #    - 80:80