version: '3.6'

services:
  web:
    build: ./src
    restart: always
    command: uwsgi --http :8000 --module srv.web:app --workers 2 --threads 2
    volumes:
      - ./src:/srv:delegated
    env_file:
      - ./.env
    links:
      - mongo
    ports:
      - 80:8000

  worker:
    build: ./src
    restart: always
    command: celery -A srv.tasks:celery worker
    volumes:
      - ./src:/srv:delegated
    environment:
      - C_FORCE_ROOT=on
    env_file:
      - ./.env
    links:
      - redis
      - mongo

  flower:
    build: ./src
    restart: always
    command: celery -A srv.tasks:celery flower --port=5555
    volumes:
      - ./src:/srv:delegated
    links:
      - redis
    env_file:
      - ./.env
    ports:
      - 5555:5555

  redis:
    image: redis:4-alpine

  mongo:
    image: mongo:4.2.2-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wildsearch_mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=wildsearch_mongo_password
      - MONGO_INITDB_DATABASE=wildsearch_mongo_db
    ports:
      - 27017:27017
    volumes:
      - ./docker-configs/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Зачем в этой схеме нужен Nginx я пока не решил
  #nginx:
  #  image: nginx:1.13-alpine
  #  volumes:
  #    - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #  depends_on:
  #    - hook_catcher
  #  ports:
  #    - 80:80