init_config:

instances:

##Log section
logs:

  - type: file
    path: "/var/log/wildsearch_app_log.json"
    service: "wildsearch_bot_telegram"
    source: python
    sourcecategory: sourcecode
    # For multiline logs, if they start by the date with the format yyyy-mm-dd uncomment the following processing rule
    #log_processing_rules:
    #  - type: multi_line
    #    name: new_log_start_with_date
    #    pattern: \d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])